### ISSUE TITLE
Code Completion Support

### ISSUE THREAD

**Issue by HoratioJSY** [VHellendoorn/Code-LMs#13]
Hi, thanks for your nice trained model~ I would like to add it to a code completion(not code generation) backend, but I cannot find an API to do this, such as using gpt cache to decode one step and go through the whole code files to calculate top-1 accuracy.

**Comment by VHellendoorn** [comment]
Hi, we currently use the GPT-Neox toolkit to generate code. It does have a function that generates tokens one step at the time [here](https://github.com/EleutherAI/gpt-neox/blob/main/megatron/text_generation_utils.py#L281), but I an imagine that's not the most practical piece to extract. We are hoping to make the model available through HuggingFace in the not too distant future; perhaps that would be helpful?

**Comment by HoratioJSY** [comment]
Thanks, this API is very helpful~
