### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by liuyongqiangjava** [VHellendoorn/Code-LMs#17]
hi,i run 2-7B model ,this is my command :sudo ./deepy.py generate.py configs/text_generation.yml checkpoints/configs/local_setup.yml checkpoints/configs/2-7B.yml，and I get this error message.
[2022-03-28 14:07:59,567] [INFO] [module.py:576:load_state_dir] RANK=0 Loaded layer=0 file=checkpoints/global_step150000/layer_00-model_00-model_states.pt

would help me solve this problem!! thanks.

**Comment by urialon** [comment]
Hi @liuyongqiangjava ,
Thank you for your interest in our work.

What is the error message? I don't see any error here.

Uri

**Comment by liuyongqiangjava** [comment]
> Hi @liuyongqiangjava , Thank you for your interest in our work.
> 
> What is the error message? I don't see any error here.
> 
> Uri

Thank you for your reply，I have found the answer，when I do inference,I should start from the offset of 16 of file ,than the error disappear
