### ISSUE TITLE
Do you guys have the plan to add kotlin sql support? 

### ISSUE THREAD

**Issue by xiaoyunwu** [VHellendoorn/Code-LMs#2]

**Comment by VHellendoorn** [comment]
We do not have plans for adding new language support in the immediate future, but I do welcome the suggestion; Kotlin has become very popular recently and would make sense to support.

My high-level take on supporting new languages is that it would make most sense to fine-tune the model on a modest corpus of code in just that language. Its multi-lingual nature would probably make it adapt quite quickly, so this could be done with significantly fewer resources. Probably a few thousand steps on Kotlin files would suffice. I will look into doing this when I have the time. What size of model are you mainly interested in?

**Comment by xiaoyunwu** [comment]
unfortunately, the language currently supported does not have what I want: kotlin/sql. So I do not know for sure. 
But as long as one gpu can do inference, I am good.
