### ISSUE TITLE
Is there pytorch_model.bin for 3 models?  Zero_to_fp32.py cannot run  

### ISSUE THREAD

**Issue by CodeGeneration2** [VHellendoorn/Code-LMs#20]
Is there pytorch_model.bin for 3 models?  Zero_to_fp32.py cannot run

**Comment by VHellendoorn** [comment]
Hi, could you provide more details on what you are unable to run? At present, the models are not available for Pytorch; if you are interested in porting them to Pytorch, that would be great.
