### ISSUE TITLE
How to fine tune the models?

### ISSUE THREAD

**Issue by smith-co** [VHellendoorn/Code-LMs#25]
Can we fine tune Polycoder?

**Comment by smith-co** [comment]
@VHellendoorn can we fine tune Polycoder? Can you provide with the steps?

**Comment by VHellendoorn** [comment]
Hi, you can fine-tune the model from any of our checkpoints by simply using the [GPT-NeoX](https://github.com/EleutherAI/gpt-neox) toolkit with a dataset of your choosing, as long as you point it to the directory containing the checkpoint files and provide the corresponding model parameter config (e.g., `2-7B.yml` for the largest model). Please follow the instructions on the aforementioned repository for steps like creating a dataset and training models.
