### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [VHellendoorn/Code-LMs#3]
There is not a LICENSE or COPYING file in the root directory so GitHub cannot parse what the license is.  Without a license, the default is copyright.  I see [a wide variety of licenses](https://github.com/VHellendoorn/Code-LMs/search?q=license) included in subdirectories including [GPL-3.0-or-later](https://github.com/VHellendoorn/Code-LMs/blob/6e4a285b90092f1e79d180a241bf4269d6c3e950/Evaluation/test_sets/Rust/Tubefeeder/Tubefeeder/src__main.rs), [AGPL-3.0-or-later](https://github.com/VHellendoorn/Code-LMs/blob/6e4a285b90092f1e79d180a241bf4269d6c3e950/Evaluation/test_sets/Scala/FlinkML/flink-jpmml/flink-jpmml-examples__src__main__scala__io__radicalbit__examples__model__Utils.scala), [LGPL-2.1-or-later](https://github.com/VHellendoorn/Code-LMs/blob/6e4a285b90092f1e79d180a241bf4269d6c3e950/Evaluation/test_sets/Scala/laforge49/Asynchronous-Functional-Programming/Blip__src__main__scala__org__agilewiki__blip__messenger__MessengerThreadFactory.scala), Apache-2.0, MIT, and others.

I am not a lawyer, but I believe that would make the repository AGPL-3.0-or-later.

**Comment by VHellendoorn** [comment]
Good catch! Resolved in [a9f3a9a](https://github.com/VHellendoorn/Code-LMs/commit/a9f3a9a3f072fd8245b4f0f30af971778801b317)
